### ISSUE TITLE
Email addresses with "+" in them are not valid in the email regex

### ISSUE THREAD

**Issue by sigmavirus24** [mdipierro/evote#21]
See https://github.com/mdipierro/evote/blob/8b48a6d449bbc1f10f34e94aafee660bf9197435/modules/ballot.py#L13 for more details

```py
>>> regex_email.findall('test+foo@gmail.com')
['foo@gmail.com']
```

**Comment by patilise** [comment]
Adapting from web2py's [validator](https://github.com/web2py/web2py/blob/b4f3784136c1db9aeab624ecd381eb2168bcb59f/gluon/validators.py) module (which adapted from [I Knew How To Validate An Email Address Until I Read The RFC](http://haacked.com/archive/2007/08/21/i-knew-how-to-validate-an-email-address-until-i.aspx/)), the following expression works:
```python
regex_email = re.compile('''^((?!\.)(?:[-a-z0-9!\#$%&'*+/=?^_`{|}~]|(?<!\.)\.)+(?<!\.)@(?:localhost|(?:[a-z0-9](?:[-\w]*[a-z0-9])?\.)+[a-z]{2,}))$''', re.IGNORECASE)
```
Although, it is not clear whether it is a good idea to support all email addresses allowed in [RFC 822](http://www.faqs.org/rfcs/rfc822.html).

**Comment by sigmavirus24** [comment]
Helios uses a separate package to manage it: https://github.com/benadida/helios-server/blob/master/requirements.txt#L25 Instead of trying to maintain this ourselves, I would suggest that *if* we want to validate email addresses, we should use a package that is maintained and used by peers.

**Comment by mdipierro** [comment]
I agree. BTW. web2py has a very good one and we have been maintaining it for here. Now sure why we are not use that since we are using the framework. I will fix it.

**Comment by sigmavirus24** [comment]
:+1: thanks @mdipierro

**Comment by mdipierro** [comment]
Fixed here: https://github.com/mdipierro/evote/commit/6a09833d5361cb43c16cb70f42f06df2f5af0fa6
