### ISSUE TITLE
Do not prompt user to login after voting successfully

### ISSUE THREAD

**Issue by dianaclarke** [mdipierro/evote#25]
After voting successfully (via the ballot link from the election email), a previously unauthenticated user is redirected to a login page. This has caused a number of users to think that their vote wasn't actually successfully cast because they weren't authenticated. The average voter doesn't ever need to login to the system, so just send them to a simple page afterwards (without a login form) thanking them for their vote.

**Comment by mdipierro** [comment]
Thanks. Fixed here: https://github.com/mdipierro/evote/commit/6a09833d5361cb43c16cb70f42f06df2f5af0fa6
